//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeSync.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeSync.Resource.default", typeof(_default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutContainer {
            get {
                return ResourceManager.GetString("AboutContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Exchange Sync.
        /// </summary>
        public static string AboutFormCaption {
            get {
                return ResourceManager.GetString("AboutFormCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Exchange Sync.
        /// </summary>
        public static string AccountInfoButtonAboutCaption {
            get {
                return ResourceManager.GetString("AccountInfoButtonAboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Exchange Sync.
        /// </summary>
        public static string AccountInfoButtonAboutExchangeSync {
            get {
                return ResourceManager.GetString("AccountInfoButtonAboutExchangeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about Exchange Sync, Support and Copyright Information.
        /// </summary>
        public static string AccountInfoButtonAboutText {
            get {
                return ResourceManager.GetString("AccountInfoButtonAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Updates.
        /// </summary>
        public static string AccountInfoButtonProductUpdates {
            get {
                return ResourceManager.GetString("AccountInfoButtonProductUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Options.
        /// </summary>
        public static string AccountInfoButtonUpdateOptions {
            get {
                return ResourceManager.GetString("AccountInfoButtonUpdateOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AccountInfoButtonVersion {
            get {
                return ResourceManager.GetString("AccountInfoButtonVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string AccountInfoContainerCaption {
            get {
                return ResourceManager.GetString("AccountInfoContainerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Activated.
        /// </summary>
        public static string AccountInfoContainerSectionProductActivated {
            get {
                return ResourceManager.GetString("AccountInfoContainerSectionProductActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Information.
        /// </summary>
        public static string AccountInfoContainerSectionProductInfo {
            get {
                return ResourceManager.GetString("AccountInfoContainerSectionProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft CRM Exchange Sync.
        /// </summary>
        public static string AccountInfoContainerSectionProductName {
            get {
                return ResourceManager.GetString("AccountInfoContainerSectionProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered To:.
        /// </summary>
        public static string AccountInfoContainerSectionRegisteredTo {
            get {
                return ResourceManager.GetString("AccountInfoContainerSectionRegisteredTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string AccountInfoContainerSectionUserInfo {
            get {
                return ResourceManager.GetString("AccountInfoContainerSectionUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AccountInfoContainerSectionVersionNumber {
            get {
                return ResourceManager.GetString("AccountInfoContainerSectionVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Multiple Groups.
        /// </summary>
        public static string AddMultipleGroups {
            get {
                return ResourceManager.GetString("AddMultipleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Group.
        /// </summary>
        public static string AddNewGroup {
            get {
                return ResourceManager.GetString("AddNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string AdministrationTab {
            get {
                return ResourceManager.GetString("AdministrationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string ChangeStatusActivate {
            get {
                return ResourceManager.GetString("ChangeStatusActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate All.
        /// </summary>
        public static string ChangeStatusActivateAll {
            get {
                return ResourceManager.GetString("ChangeStatusActivateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string ChangeStatusDeactivate {
            get {
                return ResourceManager.GetString("ChangeStatusDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate All.
        /// </summary>
        public static string ChangeStatusDeactivateAll {
            get {
                return ResourceManager.GetString("ChangeStatusDeactivateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All Exchange Aliases.
        /// </summary>
        public static string ClearAllExchangeAliases {
            get {
                return ResourceManager.GetString("ClearAllExchangeAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Log.
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string ConfirmationContainerButtonNewText {
            get {
                return ResourceManager.GetString("ConfirmationContainerButtonNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ConfirmationContainerButtonOKText {
            get {
                return ResourceManager.GetString("ConfirmationContainerButtonOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Default.
        /// </summary>
        public static string ConfirmationContainerButtonSetDefaultText {
            get {
                return ResourceManager.GetString("ConfirmationContainerButtonSetDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Email.
        /// </summary>
        public static string ConfirmationContainerButtonTestEmailText {
            get {
                return ResourceManager.GetString("ConfirmationContainerButtonTestEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Message.
        /// </summary>
        public static string ConfirmationContainerCaption {
            get {
                return ResourceManager.GetString("ConfirmationContainerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender and Recipient Information.
        /// </summary>
        public static string ConfirmationContainerSectionCaption {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cc.
        /// </summary>
        public static string ConfirmationContainerSectionCcLabel {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionCcLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string ConfirmationContainerSectionFromLabel {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string ConfirmationContainerSectionMessageLabel {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string ConfirmationContainerSectionSubjectLabel {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string ConfirmationContainerSectionTemplateLabel {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string ConfirmationContainerSectionTemplateNameLabel {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionTemplateNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string ConfirmationContainerSectionToLabel {
            get {
                return ResourceManager.GetString("ConfirmationContainerSectionToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmations.
        /// </summary>
        public static string ConfirmationsContainer {
            get {
                return ResourceManager.GetString("ConfirmationsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect Duplicates.
        /// </summary>
        public static string DetectDuplicates {
            get {
                return ResourceManager.GetString("DetectDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Active.
        /// </summary>
        public static string DisplayActive {
            get {
                return ResourceManager.GetString("DisplayActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitButton {
            get {
                return ResourceManager.GetString("ExitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Groups.
        /// </summary>
        public static string ExportGroups {
            get {
                return ResourceManager.GetString("ExportGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Log.
        /// </summary>
        public static string ExportLog {
            get {
                return ResourceManager.GetString("ExportLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackContainer {
            get {
                return ResourceManager.GetString("FeedbackContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Feedback.
        /// </summary>
        public static string FeedbackContainerButtonSubmitText {
            get {
                return ResourceManager.GetString("FeedbackContainerButtonSubmitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedbackContainerCaption {
            get {
                return ResourceManager.GetString("FeedbackContainerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string FeedbackContainerSectionMessageCaption {
            get {
                return ResourceManager.GetString("FeedbackContainerSectionMessageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string FeedbackContainerSectionSubjectCaption {
            get {
                return ResourceManager.GetString("FeedbackContainerSectionSubjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FormAddNewButtonCancelText {
            get {
                return ResourceManager.GetString("FormAddNewButtonCancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FormAddNewButtonNewText {
            get {
                return ResourceManager.GetString("FormAddNewButtonNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string FormAddNewButtonSaveText {
            get {
                return ResourceManager.GetString("FormAddNewButtonSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string FormAddNewCaption {
            get {
                return ResourceManager.GetString("FormAddNewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string FormAddNewGroupNameLabel {
            get {
                return ResourceManager.GetString("FormAddNewGroupNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select CRM List.
        /// </summary>
        public static string FormAddNewGroupSelectCRMListText {
            get {
                return ResourceManager.GetString("FormAddNewGroupSelectCRMListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Distribution Group.
        /// </summary>
        public static string FormAddNewGroupSelectDistributionGroupText {
            get {
                return ResourceManager.GetString("FormAddNewGroupSelectDistributionGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Name.
        /// </summary>
        public static string FormAddNewListNameLabel {
            get {
                return ResourceManager.GetString("FormAddNewListNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Type.
        /// </summary>
        public static string FormAddNewListTypeLabel {
            get {
                return ResourceManager.GetString("FormAddNewListTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other....
        /// </summary>
        public static string FormAddNewOtherText {
            get {
                return ResourceManager.GetString("FormAddNewOtherText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Group.
        /// </summary>
        public static string FormAddNewSectionHeader {
            get {
                return ResourceManager.GetString("FormAddNewSectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Validation.
        /// </summary>
        public static string FullValidation {
            get {
                return ResourceManager.GetString("FullValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryContainer {
            get {
                return ResourceManager.GetString("HistoryContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string HistoryContainerButtonBrowse {
            get {
                return ResourceManager.GetString("HistoryContainerButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange AutoSync.
        /// </summary>
        public static string HistoryContainerButtonExchangeAutoSync {
            get {
                return ResourceManager.GetString("HistoryContainerButtonExchangeAutoSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange ConsoleSync.
        /// </summary>
        public static string HistoryContainerButtonExchangeConsoleSync {
            get {
                return ResourceManager.GetString("HistoryContainerButtonExchangeConsoleSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Sync.
        /// </summary>
        public static string HistoryContainerButtonExchangeSync {
            get {
                return ResourceManager.GetString("HistoryContainerButtonExchangeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Logs.
        /// </summary>
        public static string HistoryContainerButtonRecentLogs {
            get {
                return ResourceManager.GetString("HistoryContainerButtonRecentLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string HistoryContainerCaption {
            get {
                return ResourceManager.GetString("HistoryContainerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsContainer {
            get {
                return ResourceManager.GetString("OptionsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Validation.
        /// </summary>
        public static string QuickValidation {
            get {
                return ResourceManager.GetString("QuickValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Group.
        /// </summary>
        public static string RemoveGroup {
            get {
                return ResourceManager.GetString("RemoveGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset CRM App Settings.
        /// </summary>
        public static string ResetCRMAppSettings {
            get {
                return ResourceManager.GetString("ResetCRMAppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Full Sync.
        /// </summary>
        public static string RunFullSync {
            get {
                return ResourceManager.GetString("RunFullSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Selected Sync.
        /// </summary>
        public static string RunSelectedSync {
            get {
                return ResourceManager.GetString("RunSelectedSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization.
        /// </summary>
        public static string SychronizationTab {
            get {
                return ResourceManager.GetString("SychronizationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        public static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
    }
}
